version: "3.4"

services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: "admin"
  #   networks:
  #     - dockerizedbe_default

  dockerizedbe:
    image: dockerizedbe
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - dockerizedbe_default
    tty: true

networks:
  dockerizedbe_default:
    external: true
