# Generated by Django 4.2.2 on 2023-11-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='casts',
            field=models.ManyToManyField(related_name='titles', to='webapp.castmember'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='webapp.genre'),
        ),
    ]
