# Generated by Django 4.2.2 on 2023-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_title_casts_title_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.URLField(),
        ),
    ]
