# Generated by Django 4.2.2 on 2023-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_title_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='trailer_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
