# Generated by Django 4.2.2 on 2023-12-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('incident_id', models.BigIntegerField()),
                ('severity', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('requester', models.EmailField(max_length=254)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('last_updated_at', models.DateField()),
                ('ci', models.CharField(max_length=10)),
            ],
        ),
    ]
