# Generated by Django 4.2.2 on 2023-12-07 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(blank=True, default='Service', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(default='No Description'),
        ),
        migrations.AddField(
            model_name='incident',
            name='subject',
            field=models.CharField(default='No Subject', max_length=1023),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_id',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(99999)]),
        ),
    ]
