# Generated by Django 4.2.2 on 2023-11-17 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tagged_to',
            field=models.ManyToManyField(blank=True, related_name='tagged_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
