# Generated by Django 4.2.2 on 2023-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
